In [ ]:
Python Values
1. Integer
2. Float
3. Boolean
4. String
5. List
6. Tuple

# array

In [ ]:
1. A list is a collection of values.
2. In a list, you can store any type of a value
3. If you have more than 1 value in the collection, then those values need to be separated with each other by a comma
4. The collection of values, in the list, needs to be surrounded by square brackets
5. Each value in the list, will have indexes(negative,positive) associated with it

1. A array is a collection of values.
2. In a array, you can only store one type of a value. If you store values of different types then python will convert it to the same type only. And this type conversion only applies when all the values are of primitive types
3. If you have more than 1 value in the collection, then those values need to be separated with each other by a comma
4. The collection of values, in the array, needs to be surrounded by square or curved brackets
5. Each value in the array, will have indexes(negative,positive) associated with it

Similarities:
1. Each value in a list, has postive and negative indexes. The same point applies to array also.
2. A list is a collection of value. Similarly, a array also is a collection of values
3. If you have more than 1 value in the collection, then those values need to be separated with each other by a comma. The same point applies to array also

Difference:
1. A list can store values of multiple datatypes. While a array can only store values of a single datatype
2. For a list, the collection of values has to be surrounded with square brackets only. Whereas, for a array, the collectio of values can be surrounded with square or curved brackets

# Create a array


In [1]:
import numpy as np

In [3]:
a=np.array([56,89.0])

In [4]:
a

array([56., 89.])

In [5]:
b=np.array((True,89,"abc"))

In [6]:
b

array(['True', '89', 'abc'], dtype='<U11')

In [8]:
type(b)

numpy.ndarray

In [9]:
type(a)

numpy.ndarray

In [10]:
c=np.array(["abc",True,(1,2,3)])

In [11]:
c

array(['abc', True, (1, 2, 3)], dtype=object)

In [12]:
d=np.array([11,22,33,44,55])

In [13]:
type(d)

numpy.ndarray

In [14]:
e=np.array((78.3,True,10.0))

In [15]:
e

array([78.3,  1. , 10. ])

In [16]:
d=np.array([11,22,33,44,55])

In [17]:
d

array([11, 22, 33, 44, 55])

# Subset single value in a array

In [19]:
d

array([11, 22, 33, 44, 55])

In [ ]:
syntax for list---


listReference[index]

In [ ]:
syntax for array---


arrayReference[index]

In [20]:
d[1]

22

In [21]:
d[-4]

22

In [22]:
d[3]

44

In [23]:
d[-5]

11

#  Subset multiple values in a array

# without slicing

In [24]:
d

array([11, 22, 33, 44, 55])

In [25]:
d[[1,3]]

array([22, 44])

In [26]:
d

array([11, 22, 33, 44, 55])

In [ ]:
syntax for array---


arrayReference[index]

In [28]:
d[[1,3,4]]

array([22, 44, 55])

In [29]:
d[[0,2]]

array([11, 33])

# with slicing

In [ ]:
only works when you want to subset multiple values

1. Whenever you want to subset multiple consecutive values from a array, you need to use the technique of slicing. Whenever you use slicing with indexes, the value at the first specified index is included, while the value at the lastSpecifiedIndex is not included. Slicing inlcudes values uptil the index that is previous to the lastSpecifiedIndex, that is closest to the lastSpecifiedIndex, and it should also be within the list
2. In slicing, you can leave out the firstSpecifiedIndex, and the lastSpecifiedIndex. If you leave out the firstSpecifiedIndex, then python will assume that you want to start from the beginning. On the other hand, if you leave out the lastSpecifiedIndex, then python will assume that you want to go uptil the end

In [ ]:
syntax:
    
arrayReference[firstSpecified:lastSpecifiedIndex]

In [30]:
d[2:]

array([33, 44, 55])

In [31]:
d[1:3]

array([22, 33])

In [32]:
d[:3]

array([11, 22, 33])

# Replace values in array

In [ ]:
In array, make sure that your number of values matches with the new number of values

While replacing also make sure that the type of the original value is the same as the type of the new value. If it is not, then the type of new value will be converted to that of original value

In [33]:
d

array([11, 22, 33, 44, 55])

In [34]:
d[2]

33

In [ ]:
syntax

current = new

In [35]:
d[2] = 78

In [36]:
d

array([11, 22, 78, 44, 55])

In [37]:
d[1]

22

In [38]:
d[1]=89.7

In [39]:
d

array([11, 89, 78, 44, 55])

In [40]:
d[3]

44

In [41]:
d[3]="abc"

ValueError: invalid literal for int() with base 10: 'abc'

In [42]:
d

array([11, 89, 78, 44, 55])

In [44]:
d

array([11, 89, 78, 44, 55])

In [45]:
d[[2,4]]

array([78, 55])

In [46]:
d[[2,4]]=[200,500,900]

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

In [47]:
d[[2,4]]=[200,500]

In [48]:
d

array([ 11,  89, 200,  44, 500])

# Similarities between list and array:


1. In a list, each value has a index (positive and negative index) ascociated with it. In a array also, each value has a index (positive and negative index) ascociated with it.
2. A list is a collection of values. Similarly, a array is also a collection of values
3. In a list, if we have more than one value in our collection then the values need to be separated by a comma. The same point applies to array also 

# Differences between list and array:

1. A list can contain values of any type. Whereas, a array can contain values of same type only
2. In a list, we surround the collection of values with square brackets. Whereas, in a array, we surround the collection of values with square or curved bracket.
3. In a list, we are not able to do mathematical operations on the values stored inside of a list. Whereas, in a array, we are able to do matheatical operations on the values stored inside of a array

In [ ]:
Predictive models (Machine Learning, Deep Learning) can only be built only if mathematical operations are performed on the data

In [ ]:
1. List
2. Tuple
3. Array

In [2]:
(1,2,3) * 2

(1, 2, 3, 1, 2, 3)

In [3]:
[1,2,3] * 2

[1, 2, 3, 1, 2, 3]

In [4]:
np.array([1,2,3]) * 2

array([2, 4, 6])

In [6]:
d=np.array([11,22,33,44,55])

In [7]:
d.ndim

1

In [8]:
e=np.array([
    [1,2,3],
    [4,5,6]
])

In [9]:
e.ndim

2

In [11]:
f=np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])

In [12]:
f.ndim

2

# Subset values in a 2d array

In [13]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
In 1D array, each value had one pair of positive and negative indexes
In 2D array, each value has two pairs of positive and negative indexes

In [ ]:
syntax for subsetting value in a 2D array:
    
arrayReference[ rowindex,columnindex ]

In [14]:
e[0 , 2]

3

In [15]:
e[0 ,1 ]

2

In [16]:
e[1,1]

5

In [18]:
e[1,2]

6

# without slicing

In [ ]:
syntax for subsetting single value in a 2D array:
    
arrayReference[ rowindex,columnindex ]

syntax for subsetting multiple values in a 2D array:
    
arrayReference[ [rowindex],[columnindex] ]

In [19]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
e[ [1,1],[0,1] ]

array([4, 5])

In [21]:
e[ [0,0,0,1],[0,1,2,1] ]

array([1, 2, 3, 5])

In [22]:
e[ [1,0,1],[0,2,2] ]

array([4, 3, 6])

# with slicing

In [ ]:
With slicing, we can only subset those values which are consecutive

1. Whenever you want to subset multiple consecutive values from a array, you need to use the technique of slicing. Whenever you use slicing with indexes, the value at the first specified index is included, while the value at the lastSpecifiedIndex is not included. Slicing inlcudes values uptil the index that is previous to the lastSpecifiedIndex, that is closest to the lastSpecifiedIndex, and it should also be within the list
2. In slicing, you can leave out the firstSpecifiedIndex, and the lastSpecifiedIndex. If you leave out the firstSpecifiedIndex, then python will assume that you want to start from the beginning. On the other hand, if you leave out the lastSpecifiedIndex, then python will assume that you want to go uptil the end

In [ ]:
syntax:
    
arrayReference[RowfirstSpecified:RowlastSpecified,columnfirstSpecified:columnlastSpecifiedIndex]

In [23]:
e[0:2 ,1:2 ]

array([[2],
       [5]])

In [24]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
e[ 0:2, 1:]

array([[2, 3],
       [5, 6]])

# Replace values in a 2D array

In [ ]:
1. The no. of new values should be equal to the number of current values 
2. The data type of the new value should be the same as the datatype of the current value

In [26]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
e[ 0, 1]

2

In [ ]:
syntax

current = new

In [28]:
e[ 0, 1] = 200

In [29]:
e

array([[  1, 200,   3],
       [  4,   5,   6]])

In [30]:
e[ 1,2 ]

6

In [31]:
e[ 1,2 ] = "60"

In [32]:
e

array([[  1, 200,   3],
       [  4,   5,  60]])

In [33]:
e[[0,1] , [1,2]]

array([200,  60])

In [34]:
e[[0,1] , [1,2]] = [2,6,9]

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

In [35]:
e[[0,1] , [1,2]] = [2,6]

In [36]:
e

array([[1, 2, 3],
       [4, 5, 6]])

# 3D array

In [38]:
c=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [39]:
c.ndim

3

In [40]:
d=np.array([
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8]
    ],
    [
        [11,12],
        [13,14],
        [15,16],
        [17,18]
        
    ],
    [
        [21,22],
        [23,24],
        [25,26],
        [27,28]
    ]
])

In [41]:
d.ndim

3

In [42]:
c=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [43]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# subset values in a 3D array

In [ ]:
In 1D array, each value had one pair of positive and negative indexes
In 2D array, each value has two pairs of positive and negative indexes
In 3D array, each value has three pairs of positive and negative indexes 

In [ ]:
c=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [ ]:
syntax for subsetting in a 3D array:
    
arrayReference[ grid index,row index ,column index ]

In [46]:
c[1 ,1 , 1]

11

In [47]:
c[0 , 1, 1]

5

In [48]:
c[1 , 0, 2]

9

In [49]:
c[0 ,1 ,2 ]

6

# without slicing

In [ ]:
syntax  for subsetting single value in a 3D array:
    
arrayReference[ grid index,row index ,column index ]

synhttp://localhost:8888/notebooks/Untitled796.ipynb#without-slicingtax  for subsetting multiple values in a 3D array:
    
arrayReference[ [grid index],[row index] ,[column index] ]

In [50]:
c[[0,1] ,[1,0] ,[2,0] ]

array([6, 7])

In [51]:
c[ [1,0,0],[1,0,0] ,[2,1,0] ]

array([12,  2,  1])

# with slicing

In [ ]:
syntax:
    
arrayReference[GridFirstSpecified:GridLastSpecified,RowFirsSpecified:RowLastSpecified,columnFirstSpecified:columnLastSpecified]

In [52]:
c[0: , 0:1,1:2 ]

array([[[2]],

       [[8]]])

In [54]:
c[0: , 0:,2: ]

array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])

# Replace values in a 3d array

In [ ]:
1. The no. of new values should be equal to the number of current values 
2. The data type of the new value should be the same as the datatype of the current value

In [ ]:
syntax

current = new

In [55]:
c[ 0,0 ,1]

2

In [56]:
c[ 0,0 ,1] = 70

In [57]:
c

array([[[ 1, 70,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [58]:
c[ 0, 0,2]

3

In [59]:
c[ 0, 0,2] = "abc"

ValueError: invalid literal for int() with base 10: 'abc'

In [60]:
c[ [0,0,1], [0,1,1], [1,2,1]]

array([70,  6, 11])

In [61]:
c[ [0,0,1], [0,1,1], [1,2,1]]=[700,600,1100]

In [62]:
c

array([[[   1,  700,    3],
        [   4,    5,  600]],

       [[   7,    8,    9],
        [  10, 1100,   12]]])