In [ ]:
Python Values
1. Integer
2. Float
3. Boolean
4. String
5. List
6. Tuple

# array

In [ ]:
1. A list is a collection of values.
2. In a list, you can store any type of a value
3. If you have more than 1 value in the collection, then those values need to be separated with each other by a comma
4. The collection of values, in the list, needs to be surrounded by square brackets
5. Each value in the list, will have indexes(negative,positive) associated with it

1. A array is a collection of values.
2. In a array, you can only store one type of a value. If you store values of different types then python will convert it to the same type only. And this type conversion only applies when all the values are of primitive types
3. If you have more than 1 value in the collection, then those values need to be separated with each other by a comma
4. The collection of values, in the array, needs to be surrounded by square or curved brackets
5. Each value in the array, will have indexes(negative,positive) associated with it

Similarities:
1. Each value in a list, has postive and negative indexes. The same point applies to array also.
2. A list is a collection of value. Similarly, a array also is a collection of values
3. If you have more than 1 value in the collection, then those values need to be separated with each other by a comma. The same point applies to array also

Difference:
1. A list can store values of multiple datatypes. While a array can only store values of a single datatype
2. For a list, the collection of values has to be surrounded with square brackets only. Whereas, for a array, the collectio of values can be surrounded with square or curved brackets

# Create a array


In [1]:
import numpy as np

In [3]:
a=np.array([56,89.0])

In [4]:
a

array([56., 89.])

In [5]:
b=np.array((True,89,"abc"))

In [6]:
b

array(['True', '89', 'abc'], dtype='<U11')

In [8]:
type(b)

numpy.ndarray

In [9]:
type(a)

numpy.ndarray

In [10]:
c=np.array(["abc",True,(1,2,3)])

In [11]:
c

array(['abc', True, (1, 2, 3)], dtype=object)

In [12]:
d=np.array([11,22,33,44,55])

In [13]:
type(d)

numpy.ndarray

In [14]:
e=np.array((78.3,True,10.0))

In [15]:
e

array([78.3,  1. , 10. ])

In [16]:
d=np.array([11,22,33,44,55])

In [17]:
d

array([11, 22, 33, 44, 55])

# Subset single value in a array

In [19]:
d

array([11, 22, 33, 44, 55])

In [ ]:
syntax for list---


listReference[index]

In [ ]:
syntax for array---


arrayReference[index]

In [20]:
d[1]

22

In [21]:
d[-4]

22

In [22]:
d[3]

44

In [23]:
d[-5]

11

#  Subset multiple values in a array

# without slicing

In [24]:
d

array([11, 22, 33, 44, 55])

In [25]:
d[[1,3]]

array([22, 44])

In [26]:
d

array([11, 22, 33, 44, 55])

In [ ]:
syntax for array---


arrayReference[index]

In [28]:
d[[1,3,4]]

array([22, 44, 55])

In [29]:
d[[0,2]]

array([11, 33])

# with slicing

In [ ]:
only works when you want to subset multiple values

1. Whenever you want to subset multiple consecutive values from a array, you need to use the technique of slicing. Whenever you use slicing with indexes, the value at the first specified index is included, while the value at the lastSpecifiedIndex is not included. Slicing inlcudes values uptil the index that is previous to the lastSpecifiedIndex, that is closest to the lastSpecifiedIndex, and it should also be within the list
2. In slicing, you can leave out the firstSpecifiedIndex, and the lastSpecifiedIndex. If you leave out the firstSpecifiedIndex, then python will assume that you want to start from the beginning. On the other hand, if you leave out the lastSpecifiedIndex, then python will assume that you want to go uptil the end

In [ ]:
syntax:
    
arrayReference[firstSpecified:lastSpecifiedIndex]

In [30]:
d[2:]

array([33, 44, 55])

In [31]:
d[1:3]

array([22, 33])

In [32]:
d[:3]

array([11, 22, 33])

# Replace values in array

In [ ]:
In array, make sure that your number of values matches with the new number of values

While replacing also make sure that the type of the original value is the same as the type of the new value. If it is not, then the type of new value will be converted to that of original value

In [33]:
d

array([11, 22, 33, 44, 55])

In [34]:
d[2]

33

In [ ]:
syntax

current = new

In [35]:
d[2] = 78

In [36]:
d

array([11, 22, 78, 44, 55])

In [37]:
d[1]

22

In [38]:
d[1]=89.7

In [39]:
d

array([11, 89, 78, 44, 55])

In [40]:
d[3]

44

In [41]:
d[3]="abc"

ValueError: invalid literal for int() with base 10: 'abc'

In [42]:
d

array([11, 89, 78, 44, 55])

In [44]:
d

array([11, 89, 78, 44, 55])

In [45]:
d[[2,4]]

array([78, 55])

In [46]:
d[[2,4]]=[200,500,900]

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

In [47]:
d[[2,4]]=[200,500]

In [48]:
d

array([ 11,  89, 200,  44, 500])